- type: entity
  id: TelecomTransmitterCircuitboard
  parent: BaseMachineCircuitboard
  name: telecommunication transmitter machine board
  description: A machine printed circuit board for an telecommunication transmitter.
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: TelecomTransmitter
    stackRequirements:
      Uranium: 15
      Steel: 15
      Cable: 5
