- type: vendingMachineInventory
  id: ERPVendingMachineServitorInventory
  startingInventory:
    LPPBigGreenButtplug: 3
    LPPMedGreenButtplug: 3
    LPPSmallGreenButtplug: 3
    LPPBigmetalButtplug: 3
    LPPMedmetalButtplug: 3
    LPPSmallmetalButtplug: 3
    LPPBigpinkButtplug: 3
    LPPMedpinkButtplug: 3
    LPPSmallpinkButtplug: 3
    LPPBigtailButtplug: 3
    LPPMedtailButtplug: 3
    LPPSmalltailButtplug: 3
    LPPBigtealButtplug: 3
    LPPMedtealButtplug: 3
    LPPSmalltealButtplug: 3
    LPPBigyellowButtplug: 3
    LPPMedyellowButtplug: 3
    LPPSmallyellowButtplug: 3
    LPPDildoAvian: 3
    LPPDildoCanine: 3
    LPPDildoDouble: 3
    LPPDildoDragon: 3
    LPPDildoEquine: 3
    LPPDildoHuman: 3
    LPPDildoTentacle: 3
    LPPPolydildoBig: 3
    LPPPolydildoMed: 3
    LPPPolydildoSmall: 3
    LPPFleshlightGreen: 3
    LPPFleshlightPink: 3
    LPPFleshlightRed: 3
    LPPFleshlightTeal: 3
    LPPFleshlightYellow: 3
    LPPPillowPinkRound: 3
    LPPPillowTealRound: 3
    LPPMaskPink: 3
    LPPClothingKblindfoldPink: 3
    LPPHypnogogglesPink: 3
    LPPMaskCyan: 3
    LPPClothingKblindfoldTeal: 3
    LPPHypnogogglesTeal: 3
    LPPVibratorGreen: 3
    LPPVibratorPink: 3
    LPPVibratorRed: 3
    LPPVibratorTeal: 3
    LPPVibratorYellow: 3
    LPPWhips: 3
    UniformJabroni: 3
    LPPClothingMaskKinkyMuzzle: 3
    LPPLatexCatsuitMale: 3
    LPPLewdmaid: 3
    LPPJanimaid: 3
    ClothingUniformJumpskirtElegantMaid: 3
    LPPClothingHeadHatMaid: 3
    ClothingCostumeBunnySuit: 3
    ClothingHeadHatBunny: 3
    LPPClothingUniformJumpsuitLacerobe: 3
    LPPBikinisBlack: 3
    LPPBikinisCyan: 3
    LPPBikinisGreen: 3
    LPPBikinisLatex: 3
    LPPBikinisOrange: 3
    LPPBikinisPurple: 3
    LPPBikinisRed: 3
    LPPBikinisTealblack: 3
    LPPBikinisWhite: 3
    LPPBikinisYellow: 3
    LPPSwimmingTrunksBlack: 3
    LPPSwimmingTrunksCyan: 3
    LPPSwimmingTrunksGreen: 3
    LPPSwimmingTrunksRed: 3
    LPPSwimmingTrunksOrange: 3
    LPPSwimmingTrunksWhite: 3
    LPPSwimmingTrunksTurquoise: 3
    LPPSwimmingTrunksYellow: 3
    LPPClothingUniformboobasuit: 3
    LPPBikinisWhiteblue: 3
    LPPBikinisWhitegreen: 3
    LPPBikinisWhiteorange: 3
    LPPBikinisWhitepurple: 3
    LPPBikinisWhitered: 3
    LPPBikinisBlackblue: 3
    LPPBikinisBlackgreen: 3
    LPPBikinisBlackorange: 3
    LPPBikinisBlackpurple: 3
    LPPBikinisBlackred: 3
    ClothingUniformSwimsuitBlue: 3
    LPPClothingBeltFlamingo: 3
    LPPClothingUniformJumpsuitSummershirt: 3
    LPPClothingUniformJumpsuitSummershirtblack: 3
    LPPClothingNeckBellCollarWhite: 3
    LPPClothingNeckBellCollarBlack: 3
    LPPClothingNeckBellCollarRed: 3
    LPPClothingNeckBellCollarCyan: 3
    LPPClothingNeckBellCollarGreen: 3
    LPPClothingNeckBellCollarPurple: 3
    LPPClothingNeckBellCollarOrange: 3
    LPPClothingNeckCollarSpiked: 3
    LPPClothingNeckCollarHeart: 3
