using System.Linq;
using System.Numerics;
using Content.Client._LP.Graphics;
using Content.Client.UserInterface.Controls;
using Content.Shared._LP.Research.TechnologyDisk.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._LP.Research.TechnologyDisk.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyDiskDecryptorWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    public event Action? OnStartManual;
    public event Action? OnStartAuto;
    public event Action? OnClaim;
    public event Action? OnLockCalibration;
    public event Action<int>? OnGridClick;
    public event Action? OnSubmitCode;
    private static readonly Color BackgroundColor = Color.FromHex("#101217e0");
    private static readonly Color EdgeColor = Color.FromHex("#3a4250");
    private static readonly Color TrackColor = Color.FromHex("#1c1f26");
    private static readonly Color TextDim = Color.FromHex("#8ba3b8");
    private static readonly Color AccentCyan = Color.FromHex("#37e5ff");
    private static readonly Color AccentTeal = Color.FromHex("#2bffb0");
    private static readonly Color AccentAmber = Color.FromHex("#ffb037");
    private static readonly Color AccentDanger = Color.FromHex("#ff3b3b");
    private static readonly Color MarkerColor = Color.FromHex("#ff2fa0");
    private static readonly Color NodeNormal = Color.FromHex("#3d4657");
    private static readonly Color NodePath = Color.FromHex("#ffd23a");
    private static readonly Color LightOn = Color.FromHex("#fff066");
    private static readonly Color LightOff = Color.FromHex("#2a3140");

    private static readonly Color ZoneColor = AccentTeal;
    private static readonly Color NodeBlocked = AccentDanger;
    private static readonly Color NodeStart = AccentCyan;
    private static readonly Color NodeEnd = AccentTeal;
    private static readonly Color CardHidden = NodeNormal;
    private static readonly Color CardFlipped = AccentCyan;
    private static readonly Color CardMatched = AccentTeal;

    // Breach colors: magenta for the picked path, yellow for legal cells
    private static readonly Color BreachIdle = Color.FromHex("#252b3d");
    private static readonly Color BreachLegal = Color.FromHex("#a89a4a");
    private static readonly Color BreachPicked = Color.FromHex("#a85a86");
    private static readonly Color BreachSequenceDone = BreachLegal;

    private static readonly Color PipeBackground = Color.FromHex("#20242c");
    private static readonly Color PipeUnsolved = Color.FromHex("#4a7d8c");
    private static readonly Color PipeSolved = AccentTeal;
    private static readonly Color PipeEndpointBg = Color.FromHex("#33291a");

    // Flow colors: cyan traced route, amber checkpoints turning green when hit
    private static readonly Color FlowNodeIdle = Color.FromHex("#232838");
    private static readonly Color FlowVisited = Color.FromHex("#2b6b78");
    private static readonly Color FlowStartColor = AccentCyan;
    private static readonly Color FlowCurrent = MarkerColor;
    private static readonly Color FlowCheckpointPending = Color.FromHex("#8a6d1a");
    private static readonly Color FlowCheckpointHit = AccentTeal;
    private static readonly Color FlowIdleLine = LightOff;
    private static readonly Color FlowTracedLine = AccentCyan;

    private static readonly Color PatternShown = NodePath;
    private static readonly Color PatternHidden = NodeNormal;
    private static readonly Color PatternFoundColor = AccentTeal;

    private static readonly Color[] CodePalette =
        { AccentDanger, AccentCyan, NodePath, AccentTeal, BreachPicked, Color.FromHex("#ff9b3b") };

    private static readonly Color JamIdle = LightOff;
    private static readonly Color JamActive = MarkerColor;

    private static readonly Color SweepHidden = NodeNormal;
    private static readonly Color SweepFlagColor = Color.FromHex("#ff9b3b");
    private static readonly Color SweepSafe = PipeBackground;
    private static readonly Color[] SweepNumberColors =
        { TextDim, AccentCyan, AccentTeal, NodePath, SweepFlagColor, AccentDanger, BreachPicked, Color.White, Color.White };

    private PanelContainer? _zoneRect;
    private PanelContainer? _markerRect;
    private PanelContainer? _timeFill;
    private PanelContainer? _integrityFill;
    private readonly StyleBoxFlat _timeFillBox = new();
    private readonly StyleBoxFlat _integrityFillBox = new();
    private readonly StyleBoxFlat _markerBox = new();
    private const float MarkerWidth = 8f;
    private readonly List<StyleBoxSciFi> _sectionFrames = new();
    private StyleBoxSciFi? _masterFrame;
    private readonly SciFiButton StartManualButton = new();
    private readonly SciFiButton StartAutoButton = new();
    private readonly SciFiButton ClaimButton = new();
    private readonly SciFiButton LockButton = new();
    private readonly SciFiButton _codeSubmitButton = new();
    private readonly SciFiButton _sweepFlagButton = new();

    // just a memory aid for the player, never sent to the server
    private readonly HashSet<int> _sweepFlags = new();
    private bool _sweepFlagMode;
    private int _lastSweepRevealedCount = -1;
    private DiskDecryptorBoundUserInterfaceState? _lastState;

    // Pattern Recall: so FrameUpdate can hide the targets once reveal time is up
    private readonly List<SciFiButton> _patternButtons = new();
    private bool _patternRevealing;
    private TimeSpan _patternRevealEnd;

    // Frequency Bands: one row per unsolved bar, animated same as the calibration marker
    private readonly List<(Control wrapper, PanelContainer zone, PanelContainer marker, StyleBoxFlat markerBox, SciFiButton clickCatcher, float period, TimeSpan startTime, float zoneStart, float zoneWidth)> _bandRows = new();

    // cached from the last server state so FrameUpdate can animate things smoothly
    private DecryptorPhase _phase = DecryptorPhase.Idle;
    private MinigameKind _minigameKind = MinigameKind.Calibration;
    private TimeSpan _deadline;
    private float _secondsTotal;
    private TimeSpan _calibrationStartTime;
    private float _calibrationPeriod = 1f;

    public TechnologyDiskDecryptorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _masterFrame = MakeFrame(AccentCyan, BackgroundColor);
        _masterFrame.BracketSize = 24f;
        _masterFrame.Padding = 4f;
        _masterFrame.ShowGrid = true;
        _masterFrame.GridSpacing = 24f;
        MasterFrame.PanelOverride = _masterFrame;

        var headerFrame = MakeFrame(AccentCyan, BackgroundColor);
        var calibrationFrame = MakeFrame(AccentTeal, BackgroundColor);
        var gridFrame = MakeFrame(AccentAmber, BackgroundColor);
        headerFrame.ShowGrid = true;
        calibrationFrame.ShowGrid = true;
        gridFrame.ShowGrid = true;
        HeaderPanel.PanelOverride = headerFrame;
        CalibrationBox.PanelOverride = calibrationFrame;
        GridBox.PanelOverride = gridFrame;
        _sectionFrames.Add(headerFrame);
        _sectionFrames.Add(calibrationFrame);
        _sectionFrames.Add(gridFrame);

        var none = new Color(0f, 0f, 0f, 0f);
        StartManualFrame.PanelOverride = MakeFrame(AccentCyan, none, thin: true);
        StartAutoFrame.PanelOverride = MakeFrame(AccentTeal, none, thin: true);
        ClaimFrame.PanelOverride = MakeFrame(AccentDanger, none, thin: true);
        LockFrame.PanelOverride = MakeFrame(AccentTeal, none, thin: true);

        StartManualButton.HorizontalExpand = true;
        StartAutoButton.HorizontalExpand = true;
        ClaimButton.HorizontalExpand = true;
        LockButton.HorizontalExpand = true;
        StartManualFrame.AddChild(StartManualButton);
        StartAutoFrame.AddChild(StartAutoButton);
        ClaimFrame.AddChild(ClaimButton);
        LockFrame.AddChild(LockButton);

        StatusLed.PanelOverride = new StyleBoxFlat { BackgroundColor = TrackColor };

        SetupTimeBar();
        SetupIntegrityBar();
        SetupCalibrationTrack();
        SetStaticText();

        StyleActionButton(StartManualButton, AccentCyan);
        StyleActionButton(StartAutoButton, AccentTeal);
        StyleActionButton(ClaimButton, AccentDanger);
        StyleActionButton(LockButton, AccentTeal);

        StartManualButton.OnPressed += () => OnStartManual?.Invoke();
        StartAutoButton.OnPressed += () => OnStartAuto?.Invoke();
        ClaimButton.OnPressed += () => OnClaim?.Invoke();
        LockButton.OnPressed += () => OnLockCalibration?.Invoke();

        CodeSubmitFrame.PanelOverride = MakeFrame(AccentAmber, new Color(0f, 0f, 0f, 0f), thin: true);
        _codeSubmitButton.HorizontalExpand = true;
        _codeSubmitButton.Text = Loc.GetString("disk-decryptor-code-submit").ToUpperInvariant();
        StyleActionButton(_codeSubmitButton, AccentAmber);
        _codeSubmitButton.OnPressed += () => OnSubmitCode?.Invoke();
        CodeSubmitFrame.AddChild(_codeSubmitButton);

        SweepFlagFrame.PanelOverride = MakeFrame(AccentDanger, new Color(0f, 0f, 0f, 0f), thin: true);
        _sweepFlagButton.HorizontalExpand = true;
        StyleActionButton(_sweepFlagButton, AccentDanger);
        UpdateSweepFlagButtonText();
        _sweepFlagButton.OnPressed += () =>
        {
            _sweepFlagMode = !_sweepFlagMode;
            UpdateSweepFlagButtonText();
        };
        SweepFlagFrame.AddChild(_sweepFlagButton);
    }

    private static void StyleActionButton(SciFiButton button, Color accent)
    {
        button.NormalColor = new Color(accent.R * 0.08f, accent.G * 0.08f, accent.B * 0.08f, 1f);
        button.TextColor = accent;
        button.UpdateVisual();
    }

    private void SetStaticText()
    {
        IntegrityLabel.Text = Loc.GetString("disk-decryptor-integrity-label").ToUpperInvariant();
        TimeLabel.Text = Loc.GetString("disk-decryptor-time-label").ToUpperInvariant();
        CalibrationHintLabel.Text = Loc.GetString("disk-decryptor-calibration-hint");
        LockButton.Text = Loc.GetString("disk-decryptor-lock").ToUpperInvariant();
        StartManualButton.Text = Loc.GetString("disk-decryptor-start-manual").ToUpperInvariant();
        StartAutoButton.Text = Loc.GetString("disk-decryptor-start-auto").ToUpperInvariant();
        ClaimButton.Text = Loc.GetString("disk-decryptor-claim").ToUpperInvariant();
        StatusLabel.FontColorOverride = AccentCyan;
        RecipeLabel.FontColorOverride = TextDim;
        IntegrityLabel.FontColorOverride = TextDim;
        TimeLabel.FontColorOverride = TextDim;
        CalibrationHintLabel.FontColorOverride = TextDim;
    }

    private static StyleBoxSciFi MakeFrame(Color accent, Color background, bool thin = false) => new()
    {
        BackgroundColor = background,
        EdgeColor = EdgeColor,
        AccentColor = accent,
        Padding = thin ? 4f : 10f,
        BracketSize = thin ? 10f : 16f,
        BracketThickness = thin ? 1.5f : 2f,
    };

    private void SetupTimeBar()
    {
        TimeBarTrack.PanelOverride = new StyleBoxFlat { BackgroundColor = TrackColor };
        _timeFill = new PanelContainer { PanelOverride = _timeFillBox };
        TimeBarLayout.AddChild(_timeFill);
    }

    private void SetupIntegrityBar()
    {
        IntegrityTrack.PanelOverride = new StyleBoxFlat { BackgroundColor = TrackColor };
        _integrityFill = new PanelContainer { PanelOverride = _integrityFillBox };
        IntegrityLayout.AddChild(_integrityFill);
    }

    private void SetupCalibrationTrack()
    {
        CalibrationTrack.PanelOverride = new StyleBoxFlat { BackgroundColor = TrackColor };
        _zoneRect = new PanelContainer { PanelOverride = new StyleBoxFlat { BackgroundColor = ZoneColor } };
        CalibrationLayout.AddChild(_zoneRect);
        _markerBox.BackgroundColor = MarkerColor;
        _markerRect = new PanelContainer { PanelOverride = _markerBox };
        CalibrationLayout.AddChild(_markerRect);
    }

    // not laid out yet on the first frame, so fall back to something reasonable
    private static float TrackWidthOf(Control track) => track.Size.X > 1f ? track.Size.X : 300f;

    public void UpdateState(DiskDecryptorBoundUserInterfaceState state)
    {
        var idle = state.Phase == DecryptorPhase.Idle;
        var manual = state.Phase == DecryptorPhase.Manual;
        var calibration = manual && state.MinigameKind == MinigameKind.Calibration;
        var grid = manual && !calibration;

        StartManualButton.Disabled = !state.HasDisk || !idle;
        StartAutoButton.Visible = state.HasProcessor;
        StartAutoButton.Disabled = !state.HasDisk || !idle;
        ClaimButton.Disabled = idle;
        LockButton.Disabled = !calibration;

        var integrityWidth = TrackWidthOf(IntegrityTrack);
        var integrityHeight = IntegrityTrack.Size.Y > 1f ? IntegrityTrack.Size.Y : 16f;
        var integrityFraction = state.Integrity / 100f;
        _integrityFill!.MinSize = new Vector2(integrityWidth * integrityFraction, integrityHeight);
        LayoutContainer.SetPosition(_integrityFill, Vector2.Zero);
        _integrityFillBox.BackgroundColor = GetBarColor(integrityFraction);

        var ledColor = state.Phase switch
        {
            DecryptorPhase.Idle => TrackColor,
            DecryptorPhase.AutoRunning => AccentTeal,
            _ when state.Integrity < 40 => AccentDanger,
            _ => AccentCyan,
        };
        ((StyleBoxFlat)StatusLed.PanelOverride!).BackgroundColor = ledColor;

        TierLabel.Visible = state.DiskTier.HasValue;
        if (state.DiskTier is { } tier)
        {
            TierLabel.Text = Loc.GetString("disk-decryptor-tier-badge", ("tier", tier));
            TierLabel.FontColorOverride = AccentAmber;
        }

        RecipeLabel.Text = string.IsNullOrEmpty(state.MaskedRecipeName) ? Loc.GetString("disk-decryptor-recipe-none")
            : Loc.GetString("disk-decryptor-recipe-hint", ("hint", state.MaskedRecipeName));
        StatusLabel.Text = GetStatusText(state).ToUpperInvariant();
        CalibrationBox.Visible = calibration;
        GridBox.Visible = grid;

        if (calibration)
        {
            var trackWidth = TrackWidthOf(CalibrationTrack);
            var trackHeight = CalibrationTrack.Size.Y > 1f ? CalibrationTrack.Size.Y : 40f;
            var zoneX = state.CalibrationZoneStart * trackWidth;
            var zoneWidthPx = state.CalibrationZoneWidth * trackWidth;
            _zoneRect!.MinSize = new Vector2(zoneWidthPx, trackHeight);
            LayoutContainer.SetPosition(_zoneRect, new Vector2(zoneX, 0));
        }

        if (grid)
            RebuildGrid(state);

        _phase = state.Phase;
        _deadline = state.Deadline;
        _secondsTotal = state.SecondsTotal;
        _minigameKind = state.MinigameKind;
        _calibrationStartTime = state.CalibrationStartTime;
        _calibrationPeriod = state.CalibrationPeriodSeconds;
    }

    private static string GetStatusText(DiskDecryptorBoundUserInterfaceState state)
    {
        if (state.Phase == DecryptorPhase.Idle)
            return Loc.GetString("disk-decryptor-status-idle");

        if (state.Phase == DecryptorPhase.AutoRunning)
            return Loc.GetString("disk-decryptor-status-auto");

        var key = state.MinigameKind switch
        {
            MinigameKind.Calibration => "disk-decryptor-status-calibration",
            MinigameKind.Circuit => "disk-decryptor-status-circuit",
            MinigameKind.LightsOut => "disk-decryptor-status-lightsout",
            MinigameKind.MemoryPairs => "disk-decryptor-status-memory",
            MinigameKind.Breach => "disk-decryptor-status-breach",
            MinigameKind.Pipe => "disk-decryptor-status-pipe",
            MinigameKind.Flow => "disk-decryptor-status-flow",
            MinigameKind.PatternRecall => "disk-decryptor-status-pattern",
            MinigameKind.CodeGuess => "disk-decryptor-status-code",
            MinigameKind.SignalJam => "disk-decryptor-status-jam",
            MinigameKind.FrequencyBands => "disk-decryptor-status-bands",
            MinigameKind.MineSweep => "disk-decryptor-status-sweep",
            _ => "disk-decryptor-status-idle",
        };

        return Loc.GetString(key, ("layer", state.CurrentLayer + 1), ("total", state.TotalLayers));
    }

    private void RebuildGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        var kind = state.MinigameKind;
        var isFlow = kind == MinigameKind.Flow;
        var isCode = kind == MinigameKind.CodeGuess;
        var isBands = kind == MinigameKind.FrequencyBands;
        var isGrid = !isFlow && !isCode && !isBands;

        PuzzleGrid.Visible = isGrid;
        FlowCanvasTrack.Visible = isFlow;
        CodeRow.Visible = isCode;
        CodeSubmitFrame.Visible = isCode;
        BandsContainer.Visible = isBands;
        PuzzleGrid.RemoveAllChildren();
        SequenceRow.Visible = kind == MinigameKind.Breach;
        SweepFlagFrame.Visible = kind == MinigameKind.MineSweep;
        _lastState = state;

        GridHintLabel.FontColorOverride = kind is MinigameKind.MineSweep or MinigameKind.Breach ? AccentDanger : TextDim;

        switch (kind)
        {
            case MinigameKind.Circuit: BuildCircuitGrid(state); break;
            case MinigameKind.LightsOut: BuildLightsGrid(state); break;
            case MinigameKind.MemoryPairs: BuildMemoryGrid(state); break;
            case MinigameKind.Pipe: BuildPipeGrid(state); break;
            case MinigameKind.PatternRecall: BuildPatternGrid(state); break;
            case MinigameKind.CodeGuess: BuildCodeGuess(state); break;
            case MinigameKind.SignalJam: BuildSignalJamGrid(state); break;
            case MinigameKind.FrequencyBands: BuildFrequencyBands(state); break;
            case MinigameKind.MineSweep: BuildMineSweepGrid(state); break;
            case MinigameKind.Flow: BuildFlowNetwork(state); break;
            case MinigameKind.Breach: BuildBreachGrid(state); break;
        }

        GridInfoLabel.FontColorOverride = AccentAmber;
    }

    private void BuildCircuitGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        PuzzleGrid.Columns = Math.Max(1, state.CircuitSize);
        GridHintLabel.Text = Loc.GetString("disk-decryptor-circuit-hint");
        GridInfoLabel.Text = Loc.GetString("disk-decryptor-circuit-moves", ("moves", state.CircuitMovesLeft));

        var blocked = state.CircuitBlocked;
        var path = state.CircuitPath;
        var total = state.CircuitSize * state.CircuitSize;
        var buttonSize = GridButtonSize(state.CircuitSize);

        for (var i = 0; i < total; i++)
        {
            var index = i;
            var isBlocked = blocked != null && index < blocked.Count && blocked[index];
            var inPath = path != null && path.Contains(index);
            var color = index switch
            {
                _ when index == state.CircuitStartIndex => NodeStart,
                _ when index == state.CircuitEndIndex => NodeEnd,
                _ when isBlocked => NodeBlocked,
                _ when inPath => NodePath,
                _ => NodeNormal,
            };

            AddGridButton(index, color, isBlocked, string.Empty, buttonSize);
        }
    }

    private void BuildLightsGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        PuzzleGrid.Columns = Math.Max(1, state.LightsSize);
        GridHintLabel.Text = Loc.GetString("disk-decryptor-lights-hint");

        var lights = state.LightsState;
        var onCount = lights?.Count(l => l) ?? 0;
        GridInfoLabel.Text = Loc.GetString("disk-decryptor-lights-remaining", ("count", onCount));

        var total = state.LightsSize * state.LightsSize;
        var buttonSize = GridButtonSize(state.LightsSize);
        for (var i = 0; i < total; i++)
        {
            var index = i;
            var isOn = lights != null && index < lights.Count && lights[index];
            AddGridButton(index, isOn ? LightOn : LightOff, false, string.Empty, buttonSize);
        }
    }

    private void BuildMemoryGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        PuzzleGrid.Columns = 4;
        GridHintLabel.Text = Loc.GetString("disk-decryptor-memory-hint");

        var symbols = state.MemoryVisibleSymbols ?? new List<int>();
        var matched = state.MemoryMatched;
        var pairsFound = (matched?.Count(m => m) ?? 0) / 2;
        GridInfoLabel.Text = Loc.GetString("disk-decryptor-memory-found", ("found", pairsFound), ("total", symbols.Count / 2));

        for (var i = 0; i < symbols.Count; i++)
        {
            var index = i;
            var isMatched = matched != null && index < matched.Count && matched[index];
            var value = symbols[index];
            var faceUp = value >= 0;
            var color = isMatched ? CardMatched : faceUp ? CardFlipped : CardHidden;
            var text = faceUp ? (value + 1).ToString() : "?";
            var button = new Button
            {
                MinSize = new Vector2(48, 48),
                Modulate = color,
                Disabled = isMatched,
                Text = text,
            };
            button.OnPressed += _ => OnGridClick?.Invoke(index);
            PuzzleGrid.AddChild(button);
        }
    }

    private void BuildPipeGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        PuzzleGrid.Columns = Math.Max(1, state.PipeSize);
        GridHintLabel.Text = Loc.GetString("disk-decryptor-pipe-hint");

        var baseMask = state.PipeBaseMask ?? new List<int>();
        var rotation = state.PipeRotation ?? new List<int>();
        var buttonSize = GridButtonSize(state.PipeSize);
        var solved = true;
        for (var i = 0; i < baseMask.Count; i++)
        {
            if (baseMask[i] != 0 && RotateCwClientSide(baseMask[i], rotation[i]) != baseMask[i])
            {
                solved = false;
                break;
            }
        }
        GridInfoLabel.Text = Loc.GetString(solved ? "disk-decryptor-pipe-connected" : "disk-decryptor-pipe-broken");

        for (var i = 0; i < baseMask.Count; i++)
        {
            var index = i;
            var mask = baseMask[index];
            var isEndpoint = index == state.PipeStartIndex || index == state.PipeEndIndex;
            var background = isEndpoint ? PipeEndpointBg : PipeBackground;
            var cell = new PipeCell { MinSize = new Vector2(buttonSize, buttonSize) };

            if (mask == 0)
            {
                cell.SetVisual(0, PipeUnsolved, PipeBackground, false);
            }
            else
            {
                var current = RotateCwClientSide(mask, rotation[index]);
                var cellSolved = current == mask;
                cell.SetVisual(current, cellSolved ? PipeSolved : PipeUnsolved, background, true);
                cell.OnPressed += () => OnGridClick?.Invoke(index);
            }

            PuzzleGrid.AddChild(cell);
        }
    }

    private static int RotateCwClientSide(int mask, int steps)
    {
        for (var i = 0; i < steps; i++)
        {
            mask = ((mask << 1) | (mask >> 3)) & 0b1111;
        }

        return mask;
    }

    private void BuildPatternGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        PuzzleGrid.Columns = Math.Max(1, state.PatternSize);
        GridHintLabel.Text = Loc.GetString("disk-decryptor-pattern-hint");

        var targets = state.PatternTargets ?? new List<bool>();
        var found = state.PatternFound ?? new List<bool>();
        GridInfoLabel.Text = Loc.GetString(
            "disk-decryptor-pattern-progress",
            ("found", found.Count(f => f)),
            ("total", targets.Count(t => t)));

        _patternButtons.Clear();
        _patternRevealing = _gameTiming.CurTime < state.PatternRevealEndTime;
        _patternRevealEnd = state.PatternRevealEndTime;

        var buttonSize = GridButtonSize(state.PatternSize);
        for (var i = 0; i < targets.Count; i++)
        {
            var index = i;
            var isTarget = targets[i];
            var isFound = found.Count > i && found[i];
            var color = isFound ? PatternFoundColor : _patternRevealing && isTarget ? PatternShown : PatternHidden;
            var button = new SciFiButton
            {
                MinSize = new Vector2(buttonSize, buttonSize),
                NormalColor = color,
                Disabled = isFound || _patternRevealing,
            };
            button.UpdateVisual();
            button.OnPressed += () => OnGridClick?.Invoke(index);
            PuzzleGrid.AddChild(button);

            if (!isFound)
                _patternButtons.Add(button);
        }
    }

    private void BuildCodeGuess(DiskDecryptorBoundUserInterfaceState state)
    {
        GridHintLabel.Text = Loc.GetString("disk-decryptor-code-hint");

        var feedback = state.CodeLastExact < 0
            ? Loc.GetString("disk-decryptor-code-no-feedback")
            : Loc.GetString("disk-decryptor-code-feedback", ("exact", state.CodeLastExact), ("partial", state.CodeLastPartial));
        GridInfoLabel.Text = Loc.GetString("disk-decryptor-code-attempts", ("left", state.CodeAttemptsLeft)) + "   " + feedback;

        CodeRow.RemoveAllChildren();
        var guess = state.CodeGuess ?? new List<int>();
        for (var i = 0; i < guess.Count; i++)
        {
            var index = i;
            var color = CodePalette[guess[i] % CodePalette.Length];
            var slot = new SciFiButton
            {
                MinSize = new Vector2(44, 44),
                HorizontalExpand = true,
                NormalColor = color,
            };
            slot.UpdateVisual();
            slot.OnPressed += () => OnGridClick?.Invoke(index);
            CodeRow.AddChild(slot);
        }
    }

    private void BuildSignalJamGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        PuzzleGrid.Columns = Math.Max(1, state.JamSize);
        GridHintLabel.Text = Loc.GetString("disk-decryptor-jam-hint");
        GridInfoLabel.Text = Loc.GetString("disk-decryptor-jam-progress", ("done", state.JamHitsDone), ("total", state.JamHitsNeeded));

        var total = state.JamSize * state.JamSize;
        var buttonSize = GridButtonSize(state.JamSize);
        for (var i = 0; i < total; i++)
        {
            var index = i;
            AddGridButton(index, index == state.JamActiveCell ? JamActive : JamIdle, false, string.Empty, buttonSize);
        }
    }

    private void BuildFrequencyBands(DiskDecryptorBoundUserInterfaceState state)
    {
        GridHintLabel.Text = Loc.GetString("disk-decryptor-bands-hint");

        var periods = state.BandsPeriod ?? new List<float>();
        var zoneStarts = state.BandsZoneStart ?? new List<float>();
        var zoneWidths = state.BandsZoneWidth ?? new List<float>();
        var startTimes = state.BandsStartTime ?? new List<TimeSpan>();
        var solved = state.BandsSolved ?? new List<bool>();

        GridInfoLabel.Text = Loc.GetString("disk-decryptor-bands-progress", ("done", solved.Count(s => s)), ("total", periods.Count));

        BandsContainer.RemoveAllChildren();
        _bandRows.Clear();

        for (var i = 0; i < periods.Count; i++)
        {
            var index = i;
            var solvedThis = solved.Count > i && solved[i];
            var wrapper = new PanelContainer { MinSize = new Vector2(1, 34), HorizontalExpand = true };
            var layout = new LayoutContainer();
            wrapper.AddChild(layout);

            var background = new PanelContainer { PanelOverride = new StyleBoxFlat { BackgroundColor = TrackColor } };
            layout.AddChild(background);

            var zone = new PanelContainer { PanelOverride = new StyleBoxFlat { BackgroundColor = solvedThis ? FlowCheckpointHit : ZoneColor } };
            layout.AddChild(zone);

            var markerBox = new StyleBoxFlat { BackgroundColor = MarkerColor };
            var marker = new PanelContainer { PanelOverride = markerBox, Visible = !solvedThis };
            layout.AddChild(marker);

            var clickCatcher = new SciFiButton
            {
                NormalColor = new Color(0f, 0f, 0f, 0f),
                Disabled = solvedThis,
                MinSize = new Vector2(300f, 34f),
            };
            clickCatcher.UpdateVisual();
            clickCatcher.OnPressed += () => OnGridClick?.Invoke(index);
            layout.AddChild(clickCatcher);

            LayoutContainer.SetPosition(background, Vector2.Zero);
            LayoutContainer.SetPosition(marker, Vector2.Zero);
            LayoutContainer.SetPosition(clickCatcher, Vector2.Zero);

            BandsContainer.AddChild(wrapper);

            if (!solvedThis)
            {
                _bandRows.Add((
                    wrapper,
                    zone,
                    marker,
                    markerBox,
                    clickCatcher,
                    periods.Count > i ? periods[i] : 1f,
                    startTimes.Count > i ? startTimes[i] : TimeSpan.Zero,
                    zoneStarts.Count > i ? zoneStarts[i] : 0f,
                    zoneWidths.Count > i ? zoneWidths[i] : 0.2f));
            }
        }
    }

    private void BuildMineSweepGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        PuzzleGrid.RemoveAllChildren();
        PuzzleGrid.Columns = Math.Max(1, state.SweepSize);
        GridHintLabel.Text = Loc.GetString("disk-decryptor-sweep-hint");
        UpdateSweepFlagButtonText();

        var visible = state.SweepVisible ?? new List<int>();
        var revealedCount = visible.Count(v => v >= 0);
        GridInfoLabel.Text = Loc.GetString("disk-decryptor-sweep-progress", ("count", revealedCount));

        if (revealedCount < _lastSweepRevealedCount)
            _sweepFlags.Clear();
        _lastSweepRevealedCount = revealedCount;

        var buttonSize = GridButtonSize(state.SweepSize);
        for (var i = 0; i < visible.Count; i++)
        {
            var index = i;
            var value = visible[i];
            var revealed = value >= 0;
            var flagged = !revealed && _sweepFlags.Contains(index);
            var color = revealed ? SweepSafe : flagged ? SweepFlagColor : SweepHidden;
            var text = revealed && value > 0 ? value.ToString() : flagged ? "⚑" : string.Empty;
            var button = new SciFiButton
            {
                MinSize = new Vector2(buttonSize, buttonSize),
                NormalColor = color,
                TextColor = revealed ? SweepNumberColors[Math.Clamp(value, 0, 8)] : Color.White,
                Disabled = revealed,
                Text = text,
            };
            button.UpdateVisual();
            button.OnPressed += () => OnSweepCellPressed(index);
            PuzzleGrid.AddChild(button);
        }
    }

    private void OnSweepCellPressed(int index)
    {
        if (_sweepFlagMode)
        {
            if (!_sweepFlags.Remove(index))
                _sweepFlags.Add(index);

            if (_lastState != null)
                BuildMineSweepGrid(_lastState);
            return;
        }

        if (_sweepFlags.Contains(index))
            return;

        OnGridClick?.Invoke(index);
    }

    private void UpdateSweepFlagButtonText()
    {
        _sweepFlagButton.Text = Loc.GetString(_sweepFlagMode ? "disk-decryptor-sweep-flag-on" : "disk-decryptor-sweep-flag-off").ToUpperInvariant();
        _sweepFlagButton.UpdateVisual();
    }

    private void BuildFlowNetwork(DiskDecryptorBoundUserInterfaceState state)
    {
        FlowCanvas.RemoveAllChildren();
        GridHintLabel.Text = Loc.GetString("disk-decryptor-flow-hint");

        var size = state.FlowSize;
        var open = state.FlowOpen ?? new List<bool>();
        var checkpoints = state.FlowCheckpoints ?? new List<int>();
        var path = state.FlowPath ?? new List<int>();
        var nextCheckpoint = state.FlowNextCheckpoint;
        var current = path.Count > 0 ? path[^1] : state.FlowStartIndex;

        GridInfoLabel.Text = Loc.GetString("disk-decryptor-flow-progress", ("done", nextCheckpoint), ("total", checkpoints.Count));

        const float cellSize = 26f;
        const float gap = 20f;
        const float pitch = cellSize + gap;
        FlowCanvasTrack.MinSize = new Vector2(size * pitch, size * pitch);

        for (var i = 0; i < open.Count; i++)
        {
            if (!open[i])
                continue;

            var x = i % size;
            var y = i / size;

            if (x < size - 1 && open[i + 1])
                AddFlowEdge(x, y, x + 1, y, pitch, cellSize, IsTracedEdge(path, i, i + 1));
            if (y < size - 1 && open[i + size])
                AddFlowEdge(x, y, x, y + 1, pitch, cellSize, IsTracedEdge(path, i, i + size));
        }

        for (var i = 0; i < open.Count; i++)
        {
            if (!open[i])
                continue;

            var index = i;
            var x = i % size;
            var y = i / size;
            var checkpointIndex = checkpoints.IndexOf(i);
            var isCheckpoint = checkpointIndex >= 0;
            var isHit = isCheckpoint && checkpointIndex < nextCheckpoint;
            var color = i == current ? FlowCurrent
                : isHit ? FlowCheckpointHit
                : isCheckpoint ? FlowCheckpointPending
                : i == state.FlowStartIndex ? FlowStartColor
                : path.Contains(i) ? FlowVisited
                : FlowNodeIdle;
            var node = new SciFiButton
            {
                MinSize = new Vector2(cellSize, cellSize),
                NormalColor = color,
                TextColor = Color.Black,
                Text = isCheckpoint ? (checkpointIndex + 1).ToString() : string.Empty,
            };
            node.UpdateVisual();
            node.OnPressed += () => OnGridClick?.Invoke(index);
            LayoutContainer.SetPosition(node, new Vector2(x * pitch, y * pitch));
            FlowCanvas.AddChild(node);
        }
    }

    private static bool IsTracedEdge(List<int> path, int a, int b)
    {
        for (var i = 0; i < path.Count - 1; i++)
        {
            if ((path[i] == a && path[i + 1] == b) || (path[i] == b && path[i + 1] == a))
                return true;
        }

        return false;
    }

    private void AddFlowEdge(int x0, int y0, int x1, int y1, float pitch, float cellSize, bool traced)
    {
        const float thickness = 4f;
        var color = traced ? FlowTracedLine : FlowIdleLine;

        Vector2 pos, size;
        if (y0 == y1)
        {
            pos = new Vector2(x0 * pitch + cellSize, y0 * pitch + cellSize / 2f - thickness / 2f);
            size = new Vector2(pitch - cellSize, thickness);
        }
        else
        {
            pos = new Vector2(x0 * pitch + cellSize / 2f - thickness / 2f, y0 * pitch + cellSize);
            size = new Vector2(thickness, pitch - cellSize);
        }

        var bar = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = color },
            MinSize = size,
        };
        LayoutContainer.SetPosition(bar, pos);
        FlowCanvas.AddChild(bar);
    }

    private void BuildBreachGrid(DiskDecryptorBoundUserInterfaceState state)
    {
        PuzzleGrid.Columns = Math.Max(1, state.BreachSize);
        GridHintLabel.Text = Loc.GetString("disk-decryptor-breach-hint");
        GridInfoLabel.Text = Loc.GetString("disk-decryptor-breach-buffer", ("moves", state.BreachMovesLeft));

        var codes = state.BreachCodes ?? new List<string>();
        var path = state.BreachPath ?? new List<int>();
        var sequence = state.BreachSequence ?? new List<string>();
        var size = state.BreachSize;
        var buttonSize = GridButtonSize(size);

        var matchedTail = 0;
        for (var len = Math.Min(sequence.Count, path.Count); len > 0; len--)
        {
            var offset = path.Count - len;
            var ok = true;
            for (var i = 0; i < len; i++)
            {
                if (codes.Count <= path[offset + i] || codes[path[offset + i]] != sequence[i])
                {
                    ok = false;
                    break;
                }
            }
            if (ok)
            {
                matchedTail = len;
                break;
            }
        }

        SequenceRow.RemoveAllChildren();
        for (var i = 0; i < sequence.Count; i++)
        {
            var done = i < matchedTail;
            SequenceRow.AddChild(new Label
            {
                Text = sequence[i],
                FontColorOverride = done ? BreachSequenceDone : TextDim,
            });
        }

        for (var i = 0; i < codes.Count; i++)
        {
            var index = i;
            var inPath = path.Contains(index);
            var legal = !inPath && IsLegalBreachMoveClientSide(size, path, index);
            var color = inPath ? BreachPicked : legal ? BreachLegal : BreachIdle;
            AddGridButton(index, color, inPath, codes[index], buttonSize);
        }
    }

    // mirrors the server's legality check, just to highlight legal cells
    private static bool IsLegalBreachMoveClientSide(int size, List<int> path, int index)
    {
        if (path.Count == 0)
            return index / size == 0;

        var last = path[^1];
        var needColumn = path.Count % 2 == 1;
        return needColumn ? index % size == last % size : index / size == last / size;
    }

    // bigger grids get smaller buttons so the window doesn't keep growing
    private static float GridButtonSize(int gridSize) => Math.Clamp(280f / Math.Max(1, gridSize), 28f, 48f);

    private void AddGridButton(int index, Color color, bool disabled, string text, float size)
    {
        var button = new SciFiButton
        {
            MinSize = new Vector2(size, size),
            NormalColor = color,
            TextColor = Color.White,
            Disabled = disabled,
            Text = text,
        };
        button.UpdateVisual();
        button.OnPressed += () => OnGridClick?.Invoke(index);
        PuzzleGrid.AddChild(button);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // wrap the time so sin() doesn't lose precision after hours of uptime
        var time = (float)(_gameTiming.CurTime.TotalSeconds % 1000.0);

        // slow, continuous sweep on the three big panels, each offset so they don't move in lockstep. Runs regardless of phase, it's just ambiance.
        const float sweepSeconds = 5f;
        _masterFrame!.ScanlinePosition = (time % (sweepSeconds * 1.5f)) / (sweepSeconds * 1.5f);
        for (var i = 0; i < _sectionFrames.Count; i++)
        {
            var offset = sweepSeconds * i / _sectionFrames.Count;
            _sectionFrames[i].ScanlinePosition = ((time + offset) % sweepSeconds) / sweepSeconds;
        }

        if (_phase == DecryptorPhase.Idle || _secondsTotal <= 0f)
        {
            _timeFillBox.BackgroundColor = TrackColor;
            _timeFill!.MinSize = Vector2.Zero;
            return;
        }

        var remaining = Math.Clamp((float)(_deadline - _gameTiming.CurTime).TotalSeconds, 0f, _secondsTotal);
        var fraction = remaining / _secondsTotal;
        var trackWidth = TrackWidthOf(TimeBarTrack);
        var trackHeight = TimeBarTrack.Size.Y > 1f ? TimeBarTrack.Size.Y : 16f;
        _timeFill!.MinSize = new Vector2(trackWidth * fraction, trackHeight);
        LayoutContainer.SetPosition(_timeFill, Vector2.Zero);

        // color only depends on the fraction, not on time, nothing here oscillates, so there's nothing left that could read as flicker
        _timeFillBox.BackgroundColor = GetBarColor(fraction);

        if (_phase == DecryptorPhase.Manual && _minigameKind == MinigameKind.Calibration && _markerRect != null)
        {
            var calibrationTrackWidth = TrackWidthOf(CalibrationTrack);
            var calibrationTrackHeight = CalibrationTrack.Size.Y > 1f ? CalibrationTrack.Size.Y : 40f;
            var position = GetCalibrationMarkerPosition(_gameTiming.CurTime);
            var x = position * (calibrationTrackWidth - MarkerWidth);

            _markerRect.MinSize = new Vector2(MarkerWidth, calibrationTrackHeight);
            LayoutContainer.SetPosition(_markerRect, new Vector2(x, 0));

            // gentle breathing glow so the marker reads as "live" rather than a static block sliding along a rail
            var pulse = 0.5f + 0.5f * MathF.Sin(time * 5f);
            _markerBox.BackgroundColor = LerpColor(MarkerColor, Color.White, pulse * 0.35f);
        }

        // Pattern Recall: hide the still-showing targets the instant the reveal window ends.
        if (_patternRevealing && _gameTiming.CurTime >= _patternRevealEnd)
        {
            _patternRevealing = false;
            foreach (var button in _patternButtons)
            {
                button.NormalColor = PatternHidden;
                button.Disabled = false;
                button.UpdateVisual();
            }
        }

        // Frequency Bands: same idea as the single Calibration marker, just once per active row.
        foreach (var (wrapper, zone, marker, markerBox, clickCatcher, period, startTime, zoneStart, zoneWidth) in _bandRows)
        {
            var trackW = TrackWidthOf(wrapper);
            var trackH = wrapper.Size.Y > 1f ? wrapper.Size.Y : 34f;

            clickCatcher.MinSize = new Vector2(trackW, trackH);

            zone.MinSize = new Vector2(zoneWidth * trackW, trackH);
            LayoutContainer.SetPosition(zone, new Vector2(zoneStart * trackW, 0));

            var position = GetBandPositionClientSide(period, startTime, _gameTiming.CurTime);
            marker.MinSize = new Vector2(MarkerWidth, trackH);
            LayoutContainer.SetPosition(marker, new Vector2(position * (trackW - MarkerWidth), 0));

            var pulse = 0.5f + 0.5f * MathF.Sin(time * 5f);
            markerBox.BackgroundColor = LerpColor(MarkerColor, Color.White, pulse * 0.35f);
        }
    }

    // Mirrors TechnologyDiskDecryptorSystem.GetBandPosition on the server.
    private static float GetBandPositionClientSide(float period, TimeSpan startTime, TimeSpan now)
    {
        if (period <= 0f)
            return 0f;

        var cycle = period * 2f;
        var t = (float)(now - startTime).TotalSeconds % cycle;
        if (t < 0f)
            t += cycle;

        return t < period ? t / period : 2f - t / period;
    }

    // Mirrors TechnologyDiskDecryptorSystem.GetCalibrationMarkerPosition on the server -
    // both sides work out the marker position independently from the same start time and
    // period instead of the server pushing a position every frame.
    private float GetCalibrationMarkerPosition(TimeSpan now)
    {
        var period = _calibrationPeriod;
        if (period <= 0f)
            return 0f;

        var elapsed = (float)(now - _calibrationStartTime).TotalSeconds;
        var cycle = period * 2f;
        var t = elapsed % cycle;
        if (t < 0f)
            t += cycle;

        return t < period ? t / period : 2f - t / period;
    }

    private static Color LerpColor(Color a, Color b, float t)
    {
        t = Math.Clamp(t, 0f, 1f);
        return new Color(a.R + (b.R - a.R) * t, a.G + (b.G - a.G) * t, a.B + (b.B - a.B) * t, 1f);
    }

    // green while there's plenty left, sliding through amber and into red as it gets
    // critical - shared by both the timer and the integrity bar
    private static Color GetBarColor(float fraction)
    {
        return fraction > 0.5f
            ? LerpColor(Color.Gold, Color.LimeGreen, (fraction - 0.5f) * 2f)
            : LerpColor(Color.Red, Color.Gold, fraction * 2f);
    }
}
